title: Bendeguz Borbely-I.
position: Student
#affiliation: TBD
email: borbely06@proton.me
keywords: minimal academic
cv_link: ./
github_link: https://github.com/bendeguz06
linkedin: https://www.linkedin.com/in/bendeguz-borbely-i-4996bb3b3
avatar: ./assets/img/avatar.png
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
canonical: https://bendeguz06.github.io/
remote_theme: yaoyao-liu/strata-academic
